export const AUTH_LOGIN = 'AUTH-LOGIN';
export const AUTH_REGISTER = 'AUTH-REGISTER';
export const AUTH_LOGOUT = 'AUTH-LOGOUT';
export const AUTH_UPDATE_USER = 'AUTH-UPDATE-USER';
export const AUTH_UPDATE_DESCRIPTION = 'AUTH-UPDATE-DESCRIPTION';

export const GENERAL_SET_LOCATION_FROM_MAP = 'GENERAL-SET-LOCATION-FROM-MAP';

